apiVersion: v1
kind: Service
metadata:
  name: openapi-deployment
spec:
  ports:
    - nodePort: 32462
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: openapi
  type: NodePort
